tap "adoptopenjdk/openjdk"
tap "buildpacks/tap"
tap "getsentry/tools"
tap "github/gh"
tap "homebrew/cask"
tap "homebrew/core"
tap "mongodb/brew"
tap "oven-sh/bun"
tap "sass/sass"
tap "stripe/stripe-cli"
tap "supabase/tap"
tap "tvuotila/libxmlsec1"
brew "act"
brew "openexr"
brew "webp"
brew "openssl@3"
brew "asciinema"
brew "aspell"
brew "automake"
brew "libyaml"
brew "aws-shell"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "oniguruma"
brew "bat"
brew "biome"
brew "blueutil"
brew "icu4c@77"
brew "fontconfig"
brew "glib"
brew "icu4c@76"
brew "openjdk"
brew "bundletool"
brew "bzip2"
brew "cabal-install"
brew "cloc"
brew "cmake"
brew "cmake-docs"
brew "colordiff"
brew "coreutils"
brew "ctags"
brew "curl"
brew "deno"
brew "diff-so-fancy"
brew "dive"
brew "docker"
brew "docker-clean"
brew "doitlive"
brew "duti"
brew "eot-utils"
brew "ruby"
brew "terminal-notifier"
brew "fastlane"
brew "fd"
brew "fpp"
brew "unixodbc"
brew "freetds"
brew "fzf"
brew "gawk"
brew "gnupg"
brew "pkgconf"
brew "libde265"
brew "libgeotiff"
brew "libheif"
brew "libpq"
brew "libxml2"
brew "nss"
brew "openjpeg"
brew "gdal"
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-tar"
brew "go"
brew "hadolint"
brew "helm"
brew "highlight"
brew "htop"
brew "hub"
brew "imagemagick@6"
brew "inetutils"
brew "infracost"
brew "jo"
brew "jpegoptim"
brew "jq"
brew "kotlin"
brew "ktlint"
brew "ldns"
brew "libffi"
brew "libomp", link: true
brew "libpaper"
brew "libusb-compat"
brew "localstack"
brew "lzlib"
brew "mas"
brew "mono-libgdiplus"
brew "nano"
brew "neovim"
brew "nmap"
brew "nnn"
brew "node"
brew "nvm"
brew "openapi-generator"
brew "optipng"
brew "pandoc"
brew "pcre"
brew "pgcli"
brew "pinentry-mac"
brew "pixi"
brew "pnpm"
brew "postgresql@17", restart_service: :changed
brew "pre-commit"
brew "pth"
brew "python-tabulate"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: :changed
brew "rust"
brew "rustup"
brew "shellcheck"
brew "ssh-copy-id"
brew "starship"
brew "swift-format"
brew "swiftformat"
brew "swig"
brew "the_silver_searcher"
brew "tig"
brew "tokei"
brew "translate-toolkit"
brew "tree"
brew "ttyrec"
brew "uv"
brew "vim"
brew "watchman"
brew "wget"
brew "wifi-password"
brew "woff2"
brew "yarn"
brew "yq"
brew "z"
brew "zlib"
brew "zplug"
brew "zsh"
brew "buildpacks/tap/pack"
brew "getsentry/tools/sentry-wizard"
brew "oven-sh/bun/bun"
brew "stripe/stripe-cli/stripe"
brew "supabase/tap/supabase"
cask "android-platform-tools"
cask "aws-vault"
cask "cursor"
cask "devutils"
cask "font-consolas-for-powerline"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-inconsolata-for-powerline"
cask "gpg-suite"
cask "orbstack"
cask "postman"
cask "visual-studio-code"
cask "zulu@17"
mas "1Password for Safari", id: 1569813296
mas "A Companion for SwiftUI", id: 1485436674
mas "Amphetamine", id: 937984704
mas "Bakery", id: 1575220747
mas "Code Recipes", id: 1012115120
mas "Core Data Lab", id: 1460684638
mas "Developer", id: 640199958
mas "Final Cut Pro", id: 424389933
mas "Haskell", id: 841285201
mas "Helm", id: 6479357934
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Medis", id: 1063631769
mas "MoneyWiz", id: 1511185140
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pastel", id: 413897608
mas "Pixelmator Pro", id: 1289583905
mas "Profiling Viewer", id: 1079647046
mas "Reeder", id: 1529448980
mas "reMarkable", id: 1276493162
mas "Remote Desktop", id: 409907375
mas "RocketSim", id: 1504940162
mas "Screenshot Studio", id: 6473832582
mas "Slack", id: 803453959
mas "SnippetsLab", id: 1006087419
mas "Swift Playground", id: 1496833156
mas "Telegram", id: 747648890
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Transmit", id: 1436522307
mas "Transporter", id: 1450874784
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
vscode "aeschli.vscode-css-formatter"
vscode "ahmadalli.vscode-nginx-conf"
vscode "alexdima.copy-relative-path"
vscode "be5invis.toml"
vscode "bradlc.vscode-tailwindcss"
vscode "charliermarsh.ruff"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "codezombiech.gitignore"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "deerawan.vscode-dash"
vscode "donjayamanne.githistory"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "eriklynd.json-tools"
vscode "esbenp.prettier-vscode"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.remotehub"
vscode "github.vscode-codeql"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "gruntfuggly.todo-tree"
vscode "hbenl.vscode-test-explorer"
vscode "justusadam.language-haskell"
vscode "littlefoxteam.vscode-python-test-adapter"
vscode "lokalise.i18n-ally"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.debugpy"
vscode "ms-python.mypy-type-checker"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.test-adapter-converter"
vscode "mtxr.sqltools"
vscode "prisma.prisma"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "shakram02.bash-beautify"
vscode "shopify.ruby-lsp"
vscode "sibiraj-s.vscode-scss-formatter"
vscode "sswg.swift-lang"
vscode "streetsidesoftware.code-spell-checker"
vscode "teabyii.ayu"
vscode "tim-koehler.helm-intellisense"
vscode "vadimcn.vscode-lldb"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "visualstudioexptteam.vscodeintellicode-completions"
vscode "visualstudioexptteam.vscodeintellicode-insiders"
vscode "wakatime.vscode-wakatime"
vscode "yzhang.markdown-all-in-one"
