tap "1password/tap"
tap "adoptopenjdk/openjdk"
tap "bramstein/webfonttools"
tap "buildpacks/tap"
tap "d12frosted/emacs-plus"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "nektos/tap"
tap "sass/sass"
tap "wagoodman/dive"
tap "weaveworks/tap"
brew "act"
brew "libyaml"
brew "ansible"
brew "ansible-lint"
brew "openexr"
brew "webp"
brew "bzip2"
brew "asciinema"
brew "aspell"
brew "automake"
brew "aws-shell"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "blueutil"
brew "cabal-install"
brew "fontconfig"
brew "glib"
brew "libffi"
brew "pkg-config"
brew "pcre"
brew "cgal"
brew "cloc"
brew "cmake"
brew "ruby"
brew "cocoapods"
brew "colordiff"
brew "coreutils"
brew "ctags"
brew "curl"
brew "diff-so-fancy"
brew "docker"
brew "docker-clean"
brew "doctl"
brew "doitlive"
brew "duti"
brew "unixodbc"
brew "elixir"
brew "eot-utils"
brew "exa"
brew "fd"
brew "woff2"
brew "fontforge"
brew "fpp"
brew "freetds"
brew "fzf"
brew "gawk"
brew "libde265"
brew "libgeotiff"
brew "libheif"
brew "libpq"
brew "libxml2"
brew "nss"
brew "openjpeg"
brew "gdal"
brew "geoip"
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-tar"
brew "gnupg"
brew "go"
brew "graphviz"
brew "libpaper"
brew "hadolint"
brew "helm"
brew "highlight"
brew "htop"
brew "hub"
brew "hugo"
brew "libomp", link: true
brew "imagemagick"
brew "imagemagick@6"
brew "inetutils"
brew "infracost"
brew "jo"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "openjdk"
brew "kotlin"
brew "ldns"
brew "lftp"
brew "libusb-compat"
brew "libxmlsec1"
brew "lzlib"
brew "mailhog", restart_service: true
brew "mas"
brew "mono-libgdiplus"
brew "nano"
brew "neovim"
brew "nmap"
brew "nnn"
brew "node"
brew "nvm"
brew "openapi-generator"
brew "openssl@3"
brew "optipng"
brew "pandoc"
brew "python-tabulate"
brew "pgcli"
brew "pinentry-mac"
brew "postgresql@14", restart_service: true
brew "sfcgal"
brew "postgis"
brew "pre-commit"
brew "pth"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.8"
brew "rabbitmq"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "rust"
brew "rustup-init"
brew "shellcheck"
brew "ssh-copy-id"
brew "starship"
brew "swift-format"
brew "swiftformat"
brew "swig"
brew "terminal-notifier"
brew "terraform"
brew "terragrunt"
brew "the_silver_searcher"
brew "tig"
brew "tinc"
brew "tldr"
brew "tokei"
brew "translate-toolkit"
brew "tree"
brew "ttyrec"
brew "ttygif"
brew "vim"
brew "watchman"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "z"
brew "zlib"
brew "zplug"
brew "zsh"
brew "buildpacks/tap/pack"
brew "d12frosted/emacs-plus/emacs-plus@27"
brew "wagoodman/dive/dive"
brew "weaveworks/tap/eksctl"
cask "1password-cli"
cask "android-platform-tools"
cask "aws-vault"
cask "dotnet"
cask "font-consolas-for-powerline"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-inconsolata-for-powerline"
cask "gpg-suite"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "suspicious-package"
cask "tunnelblick"
cask "visual-studio-code"
cask "webpquicklook"
cask "wkhtmltopdf"
mas "1Password for Safari", id: 1569813296
mas "A Companion for SwiftUI", id: 1485436674
mas "Adobe Lightroom", id: 1451544217
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "Bakery", id: 1575220747
mas "Code Recipes", id: 1012115120
mas "Developer", id: 640199958
mas "DevUtils", id: 1533756032
mas "DjVu Reader Pro", id: 895264364
mas "GarageBand", id: 682658836
mas "Grammarly for Safari", id: 1462114288
mas "Haskell", id: 841285201
mas "iMovie", id: 408981434
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Magic Lasso", id: 1198047227
mas "Magnet", id: 441258766
mas "Medis", id: 1063631769
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "MoneyWiz", id: 1511185140
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Playgrounds", id: 1496833156
mas "Reeder", id: 1529448980
mas "Remote Desktop", id: 409907375
mas "Slack", id: 803453959
mas "SnippetsLab", id: 1006087419
mas "Telegram", id: 747648890
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Transmit", id: 1436522307
mas "Transporter", id: 1450874784
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
