# source files with vscode
duti -s com.microsoft.VSCode .S all
duti -s com.microsoft.VSCode .asp all
duti -s com.microsoft.VSCode .bat all
duti -s com.microsoft.VSCode .c all
duti -s com.microsoft.VSCode .cc all
duti -s com.microsoft.VSCode .cfg all
duti -s com.microsoft.VSCode .cgi all
duti -s com.microsoft.VSCode .conf all
duti -s com.microsoft.VSCode .config all
duti -s com.microsoft.VSCode .cpp all
duti -s com.microsoft.VSCode .cs all
duti -s com.microsoft.VSCode .css all
duti -s com.microsoft.VSCode .csv all
duti -s com.microsoft.VSCode .dat all
duti -s com.microsoft.VSCode .dtd all
duti -s com.microsoft.VSCode .duti all
duti -s com.microsoft.VSCode .erl all
duti -s com.microsoft.VSCode .h all
duti -s com.microsoft.VSCode .hs all
duti -s com.microsoft.VSCode .hpp all
duti -s com.microsoft.VSCode .hrl all
duti -s com.microsoft.VSCode .htm editor
duti -s com.microsoft.VSCode .html editor
duti -s com.microsoft.VSCode .ini all
duti -s com.microsoft.VSCode .java all
duti -s com.microsoft.VSCode .js all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .jsp editor
duti -s com.microsoft.VSCode .less all
duti -s com.microsoft.VSCode .lisp all
duti -s com.microsoft.VSCode .log all
duti -s com.microsoft.VSCode .m all
duti -s com.microsoft.VSCode .markdown all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .pch all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .pl all
duti -s com.microsoft.VSCode .plist editor
duti -s com.microsoft.VSCode .py all
duti -s com.microsoft.VSCode .rb all
duti -s com.microsoft.VSCode .rs all
duti -s com.microsoft.VSCode .rst all
duti -s com.microsoft.VSCode .scss all
duti -s com.microsoft.VSCode .sh all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .tex all
duti -s com.microsoft.VSCode .xhtml editor
duti -s com.microsoft.VSCode .xml all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .toml all
duti -s com.microsoft.VSCode Makefile all
duti -s com.microsoft.VSCode Rakefile all
duti -s com.microsoft.VSCode README all
duti -s com.microsoft.VSCode public.plain-text all
duti -s com.microsoft.VSCode public.shell-script all
duti -s com.microsoft.VSCode public.unix-executable all
