code --install-extension EditorConfig.EditorConfigr
code --install-extension alexdima.copy-relative-path
code --install-extension azeemba.python-ast-preview
code --install-extension codezombiech.gitignore
code --install-extension dakshmiglani.hex-to-rgba
code --install-extension donjayamanne.githistory
code --install-extension dotjoshjohnson.xml
code --install-extension eamodio.gitlens
code --install-extension felipe.nasc-touchbar
code --install-extension justusadam.language-haskell
code --install-extension justusadam.yzhang.markdown-all-in-one
code --install-extension lextudio.restructuredtext
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.go
code --install-extension njpwerner.autodocstring
code --install-extension redhat.vscode-yaml
code --install-extension shakram02.bash-beautify
code --install-extension shamanu4.django-intellisense
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension visualstudioexptteam.vscodeintellicode
