code --install-extension 42crunch.vscode-openapi
code --install-extension EditorConfig.EditorConfig
code --install-extension aeschli.vscode-css-formatter
code --install-extension alanz.vscode-hie-server
code --install-extension alexdima.copy-relative-path
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension be5invis.toml
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension dariofuzinato.vue-peek
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eriklynd.json-tools
code --install-extension felipe.nasc-touchbar
code --install-extension github.github-vscode-theme
code --install-extension hbenl.vscode-test-explorer
code --install-extension justusadam.language-haskell
code --install-extension justusadam.yzhang.markdown-all-in-one
code --install-extension lextudio.restructuredtext
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension MaxGabriel.brittany
code --install-extension mechatroner.rainbow-csv
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.cpptools
code --install-extension ms-python.python
code --install-extension ms-vscode.go
code --install-extension ms-vscode.sublime-keybindings
code --install-extension mtxr.sqltools
code --install-extension njpwerner.autodocstring
code --install-extension octref.vetur
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension shakram02.bash-beautify
code --install-extension shamanu4.django-intellisense
code --install-extension stevejpurves.cucumber
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension teabyii.ayu
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscode-drawio
