code --install-extension 42Crunch.vscode-openapi
code --install-extension aeschli.vscode-css-formatter
code --install-extension alexdima.copy-relative-path
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension be5invis.toml
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension dariofuzinato.vue-peek
code --install-extension Dart-Code.dart-code
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eriklynd.json-tools
code --install-extension felipe.nasc-touchbar
code --install-extension formulahendry.github-actions
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension haskell.haskell
code --install-extension hbenl.vscode-test-explorer
code --install-extension hediet.vscode-drawio
code --install-extension justusadam.language-haskell
code --install-extension lextudio.restructuredtext
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension mattn.Lisp
code --install-extension MaxGabriel.brittany
code --install-extension mechatroner.rainbow-csv
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension mtxr.sqltools
code --install-extension njpwerner.autodocstring
code --install-extension octref.vetur
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension shakram02.bash-beautify
code --install-extension shamanu4.django-intellisense
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension stevejpurves.cucumber
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension teabyii.ayu
code --install-extension Tim-Koehler.helm-intellisense
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WakaTime.vscode-wakatime
code --install-extension wingrunr21.vscode-ruby
code --install-extension yzhang.markdown-all-in-one
